#!/usr/bin/env bash
if [[ ! -f "$0.env" ]] ; then
  printf "$(tput setaf 1)$(tput bold)Error:$(tput sgr0) environment varibale file not set\n"
  printf "    1. Run $(tput setaf 2)contab -e$(tput sgr0)\n"
  printf "    2. Add the line $(tput setaf 2)* * * * * /usr/bin/env > \"$0.env\"$(tput sgr0)\n"
  printf "    3. Save and exit\n"
  printf "    4. Wait for 59 seconds\n"
  printf "    5. Run $(tput setaf 2)contab -e$(tput sgr0) again\n"
  printf "    6. Remove the line you added, save, exit\n"
  printf "    7. Done, now you can use $(tput setaf 2)$0$(tput sgr0) to test your cron commands\n\n"
  exit 1
fi
. "$0.env"
exec /usr/bin/env -i "$SHELL" -c "set -a;. $0.env; $1"
